# Generated by Django 4.2.3 on 2023-07-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("content", models.TextField(max_length=10000)),
                ("created_at", models.DateTimeField()),
                ("published", models.BooleanField(default=False)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("views_count", models.IntegerField(default=0)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("WD", "Web Development"),
                            ("AD", "Android Development"),
                            ("DD", "Desktop Development"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
